default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: meetingsurvey_development

test: &test
  <<: *default
  database: meetingsurvey_test

production:
  <<: *default
  database: meetingsurvey_production
  password: <%= ENV['MEETINGSURVEY_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test